#!/usr/bin/env bun
/**
 * Rasterize linux/platter.svg to raw ARGB32 pixmaps at the sizes panels
 * care about and write them into src/tray/icon-data.ts as base64-encoded
 * byte literals. This file is committed so the compiled binary never needs
 * a runtime SVG rasterizer, and panels that ignore IconName/IconThemePath
 * still get a crisp icon straight out of IconPixmap.
 *
 * Run `bun run build:icons` (or just `bun run compile`) to regenerate.
 * Requires ImageMagick — either IM7 (`magick`) or IM6 (`convert`) on PATH.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SIZES = [16, 22, 24, 32, 48, 64] as const;
const SVG_PATH = join(import.meta.dir, "..", "linux", "platter.svg");
const OUT_PATH = join(import.meta.dir, "..", "src", "tray", "icon-data.ts");

if (!existsSync(SVG_PATH)) {
  console.error(`Missing source SVG at ${SVG_PATH}`);
  process.exit(1);
}

function findImageMagick(): string {
  for (const bin of ["magick", "convert"]) {
    try {
      execFileSync(bin, ["-version"], { stdio: "ignore" });
      return bin;
    } catch {
      // try next candidate
    }
  }
  throw new Error("ImageMagick not found — install IM7 (`magick`) or IM6 (`convert`) on PATH.");
}

const IM_BIN = findImageMagick();

function rasterize(size: number): Buffer {
  const tmp = `/tmp/platter-icon-${size}.rgba`;
  try {
    execFileSync(
      IM_BIN,
      [
        "-background",
        "none",
        "-density",
        String(size * 4),
        SVG_PATH,
        "-resize",
        `${size}x${size}`,
        "-depth",
        "8",
        `rgba:${tmp}`,
      ],
      { stdio: ["ignore", "ignore", "inherit"] },
    );
    const rgba = readFileSync(tmp);
    if (rgba.length !== size * size * 4) {
      throw new Error(`expected ${size * size * 4} bytes, got ${rgba.length}`);
    }
    // Swap RGBA → ARGB (big-endian byte order for SNI).
    const argb = Buffer.alloc(rgba.length);
    for (let i = 0; i < rgba.length; i += 4) {
      argb[i] = rgba[i + 3]!; // A
      argb[i + 1] = rgba[i]!; // R
      argb[i + 2] = rgba[i + 1]!; // G
      argb[i + 3] = rgba[i + 2]!; // B
    }
    return argb;
  } finally {
    try {
      unlinkSync(tmp);
    } catch {
      // best effort
    }
  }
}

const entries: Array<{ size: number; b64: string }> = [];
for (const size of SIZES) {
  process.stderr.write(`rasterizing ${size}x${size}... `);
  const buf = rasterize(size);
  entries.push({ size, b64: buf.toString("base64") });
  process.stderr.write(`${buf.length} bytes\n`);
}

const body = entries
  .map((e) => `  { size: ${e.size}, data: Buffer.from("${e.b64}", "base64") },`)
  .join("\n");

const svgB64 = readFileSync(SVG_PATH).toString("base64");

const content = `/**
 * Auto-generated by scripts/build-icon-data.ts — DO NOT EDIT BY HAND.
 * Run \`bun run build:icons\` to regenerate from linux/platter.svg.
 *
 * Each entry is an ARGB32 pixmap (big-endian, row-major) sized NxN. Served
 * verbatim from the tray's StatusNotifierItem IconPixmap property so panels
 * don't have to do any icon theme lookups to draw us.
 */

export interface RasterizedIcon {
  size: number;
  data: Buffer;
}

export interface Argb32Pixmap {
  width: number;
  height: number;
  /** ARGB32, big-endian, row-major. Length = width * height * 4. */
  data: Buffer;
}

/**
 * Multi-size rasterized pixmaps generated at build time from
 * \`linux/platter.svg\`. Returned directly from SNI's \`IconPixmap\` so panels
 * can render the cloche without doing any icon theme lookups.
 */
export function buildRasterizedPixmaps(): Argb32Pixmap[] {
  return PLATTER_ICON_SIZES.map((r) => ({ width: r.size, height: r.size, data: r.data }));
}

export const PLATTER_ICON_SIZES: RasterizedIcon[] = [
${body}
];

/**
 * Raw SVG bytes for \`linux/platter.svg\`, embedded so the compiled binary
 * can materialize an icon file on disk (used as \`notify-send --icon\`).
 */
export const PLATTER_ICON_SVG: Buffer = Buffer.from("${svgB64}", "base64");
`;

writeFileSync(OUT_PATH, content);

// Long base64 literals trip Biome's line-width formatter; run it now so the
// generated file doesn't leave the repo in a lint-failing state.
try {
  execFileSync("bun", ["x", "biome", "format", "--write", OUT_PATH], { stdio: "inherit" });
} catch {
  // Biome is a devDependency; if it's unavailable the committed file may
  // need a follow-up `bun run format`.
}

console.error(`Wrote ${OUT_PATH} (${entries.length} sizes)`);
